### ISSUE TITLE
Migrate to GH pages

### ISSUE THREAD

**Issue by hofbi** [latex4ei/Allgemein#9]
I added mkdocs to deploy this repo to gh pages as a replacement for the old website.

See https://latex4ei.github.io/Allgemein/ as preview.

Once everyone is happy, we could switch latex4ei.de to point to this gh page.

**Comment by hofbi** [comment]
@dariusptrs @emareg

**Comment by hofbi** [comment]
One thing I just realized, I used the wrong logo. https://github.com/latex4ei/Allgemein/blob/master/docs/img/Logo.png has to be updated with the Latex4ei one

**Comment by dariusptrs** [comment]
It looks very good to me 👍

One thing I would still change is that I would replace the CI status badge with the time of last commit. A badge for that can be generated with this url https://img.shields.io/github/last-commit/latex4ei/:repo_name. I already made those changes in [develop](https://github.com/latex4ei/Allgemein/tree/develop) for you to see. There is also the possibility to change the text `last commit` to something else.

**Comment by hofbi** [comment]
Could you update your branch and create a PR. Then it is easier to review and discuss

**Comment by dariusptrs** [comment]
I added all external cheat sheets to [latex4ei/external](https://github.com/latex4ei/external) and included the about us page from the old website.

So I think everything important has been added and we are ready to migrate.

**Comment by hofbi** [comment]
@emareg @martinzellner What do you think?

**Comment by dariusptrs** [comment]
So, whats the plan now?

Can we contact them somehow else maybe? 🤔

**Comment by martinzellner** [comment]
Sorry for the late reply. I'm pretty busy until next Monday. I can take a look at the new website after that. I hope that's okay :)

**Comment by emareg** [comment]
Sorry for being late to the party, was on vacation. I think it is a very good idea to move everything to GitHub and the page looks fine to me. I'm also glad that the project is still alive 😃 

I just want to throw in the idea whether we could merge this with https://www.tex4tum.de/sheets/? It is also based on mkdocs and the idea of tex4tum.de was to have the important and common parts of the cheat sheets easily available as short interactive online pages while still serving the full PDF sheets for printing. The problem is that tex4tum is still not very mature. But if it was possible to just maintain one GH page environment based on mkdocs that would make a lot of sense to me. 

Maybe we could just hide most of the articles on tex4tum that are not finished yet and have the PDF sheets on the frontpage? So the focus is still on the printable sheets as before but people can explore some of the tex4tum articles and maybe we get more feedback on whether interactive cheat sheets would be worth improving. Plus we only need to care about one pipeline and GH page. Both domains could point to the same page.

**Comment by hofbi** [comment]
I also took that into consideration. I was just not sure if we would want to redirect latex4ei.de to this subpage.

To still tex4tum back in the game, I know that you can have subprojects with mkdocs, so we could make the new latex4ei page on github a subproject of tex4tum (or the other way round if we want).

To not stop the progress and discard what we have done so far, my recommendation would be to

1. switch latex4ei.de to point to https://latex4ei.github.io/Allgemein/
2. check the diff between https://latex4ei.github.io/Allgemein/ and https://www.tex4tum.de/sheets/ and merge into https://latex4ei.github.io/Allgemein/
3. make https://latex4ei.github.io/Allgemein/ to be available as subproject at https://www.tex4tum.de/sheets/ or simply make the sheets button on tex4tum forward to latex4ei.de again and delete the duplicate content from https://www.tex4tum.de/sheets/

**Comment by dariusptrs** [comment]
I created a Project for tracking the progress. We could add all the To-Dos in there and then slowly integrate one website into the other.

**Comment by emareg** [comment]
Perfect :) Since tex4tum probably has the more complex build pipeline to support all the features I would use this as the base and then completely replace https://www.tex4tum.de/sheets/ (it's old and outdated snapshot of latex4ei) with the new and shiny https://latex4ei.github.io/Allgemein/

The question is whether the sheets should be on the frontpage as well? Should we rename the page tex4tum to latex4ei and have a "tex4tum" section? Or should we keep tex4tum as name and have a "latex4ei" tab/section on that page? Since the sheets are currently the reason why students visit the website I would still have them in the focus and make sure that "latex4ei.de" keeps pointing directly at those PDF files.

**Comment by hofbi** [comment]
Maybe we keep both and cross link them. The sheets section on tex4tum points to Latex4ei and on Latex4ei we link to tex4tum.

**Comment by dariusptrs** [comment]
Since google search results mostly show `www.latex4ei.de` instead of `latex4ei.de` it might make more sense to move this page to the www domain and set up a redirect for the non-www domain.

**Comment by dariusptrs** [comment]
Maybe we can set up a `302` temporary redirect to `latex4ei.github.io/Allgemein` until the domain settings are updated.

**Comment by martinzellner** [comment]
Domain settings are updated ✅

**Comment by martinzellner** [comment]
...but we don't have HTTPS (yet). Not sure what is missing here. Maybe we just need to wait a bit for the DNS to properly propagate...
![image](https://github.com/user-attachments/assets/ed3c5664-1bdf-41f1-8202-4d8e69b53ce7)

**Comment by martinzellner** [comment]
And what do we do with the email address?

**Comment by dariusptrs** [comment]
> ...but we don't have HTTPS (yet). Not sure what is missing here. Maybe we just need to wait a bit for the DNS to properly propagate... ![image](https://private-user-images.githubusercontent.com/855054/372146215-ed3c5664-1bdf-41f1-8202-4d8e69b53ce7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MTIzNjMsIm5iZiI6MTcyNzcxMjA2MywicGF0aCI6Ii84NTUwNTQvMzcyMTQ2MjE1LWVkM2M1NjY0LTFiZGYtNDFmMS04MjAyLTRkOGU2OWI1M2NlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQxNjAxMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGZlMTJmNWNhYjg1YjNmNzYzMGVkOTExN2E0YTA5NjQ1OGZmZGYyY2Y2YTA5MmE5YWU5ZTkwMTUyYTUyNmM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NLvah6mJN0JANBnDn_9RK3zF60y-S3Y7KNNPqiCno50)

`latex4ei.de` works now (with https). I just read the docs and I think that `www.latex4ei.de` needs a CNAME record to `latex4ei.github.io` aswell as a 301 redirect to `latex4ei.de` (if that is possible in the domain settings). Otherwise we maybe just have to leave it on the old webserver and set up a 301 redirect to the new `latex4ei.de` there.

@hofbi What do you think?

**Comment by dariusptrs** [comment]
maybe it will also work like this already if we wait some time.

**Comment by hofbi** [comment]
Let's give it some time and check later again.

**Comment by martinzellner** [comment]
Works now. Setting the CNAME entry for the `www` subdomain helped.
Check yourself: https://www.latex4ei.de
